version: "3.9"
services: 
    testgo:
      build:
        context: ./goutils
        dockerfile: go.dockerfile
      tty: true
      command: bash
      volumes: 
        - ./goutils/conf:/home/xxx/conf
    testc:
      build:
        context: ./cutils
          dockerfile: c.dockerfile
    testpy:
      build:
        context: ./pyutils
          dockerfile: py.dockerfile

