version: "3.9"
services: 
    testgo:
      build:
        context: ./goutils
        dockerfile: go.dockerfile
      tty: true
      volumes: 
        - ./goutils/conf:/home/xxx/conf
    testc:
      build:
        context: ./cutils
        dockerfile: c.dockerfile
      tty: true
    testpy:
      build:
        context: ./pyutils
        dockerfile: py.dockerfile
      tty: true

