name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: | 
        go build -o app ./main.go
        ./app
      working-directory: ./goutils

    - name: Set up C
      run: |
        gcc --version
        gcc -o copy ./copy.c
        ./copy ../goutils/go.dockerfile c.dockerfile
        cat c.dockerfile
      working-directory: ./cutils
    
    - name: Set up Python
      run: |
        python --version